kind: pipeline
name: {{ cookiecutter.project_name_pretty_platform }}

steps:

# ------------------------------------------------------------------------------

- name: Build Development
  image: node:16
  username: DOCKER_USER
  password: DOCKER_PASS
  commands:
  - npm install --quiet
  - npm run build
  environment:
    GOOGLE_MAPS_KEY: ''
  when:
    branch: dev
    event:
    - push
    - pull_request


- name: Deploy Development to S3 & Invalidate CloudFront Cache
  image: samepagelabs/awscli:latest
  username: DOCKER_USER
  password: DOCKER_PASS
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: {{ cookiecutter.aws_ci_access_key_name_dev }}
    AWS_SECRET_ACCESS_KEY:
      from_secret: {{ cookiecutter.aws_ci_secret_key_name_dev }}
    S3_URL: s3://{{ cookiecutter.s3_bucket_dev }}
    CDN_DISTRIBUTION_ID: {{ cookiecutter.cloudfront_dist_id_dev }}
  commands:
  - aws s3 rm $S3_URL/previous --recursive
  - aws s3 mv $S3_URL/latest $S3_URL/previous --recursive
  - aws s3 sync ./build $S3_URL/latest
  - aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths "/*"
  when:
    branch: dev
    event:
    - push
    # - pull_request


# ------------------------------------------------------------------------------

- name: Build Staging
  image: node:16
  username: DOCKER_USER
  password: DOCKER_PASS
  commands:
  - npm install --quiet
  - npm run build
  environment:
    GOOGLE_MAPS_KEY: ''
  when:
    branch: stage
    event:
    - push
    - pull_request

- name: Deploy Staging to S3 & Invalidate CloudFront Cache
  image: samepagelabs/awscli:latest
  username: DOCKER_USER
  password: DOCKER_PASS
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: {{ cookiecutter.aws_ci_access_key_name_stage }}
    AWS_SECRET_ACCESS_KEY:
      from_secret: {{ cookiecutter.aws_ci_secret_key_name_stage }}
    S3_URL: s3://{{ cookiecutter.s3_bucket_stage }}
    CDN_DISTRIBUTION_ID: {{ cookiecutter.cloudfront_dist_id_stage }}
  commands:
  - aws s3 rm $S3_URL/previous --recursive
  - aws s3 mv $S3_URL/latest $S3_URL/previous --recursive
  - aws s3 sync ./build $S3_URL/latest
  - aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths "/*"
  when:
    branch: stage
    event:
    - push
    # - pull_request

# # Keep commented out before deploying on produciton:
# # ------------------------------------------------------------------------------

# - name: Build Production
#   image: node:16
#   commands:
#   - npm install --quiet
#   - npm run build
#   environment:
#     GOOGLE_MAPS_KEY: ''
#   when:
#     branch: master
#     event:
#     - push
#     - pull_request

# - name: Deploy Production to S3 & Invalidate CloudFront Cache
#   image: samepagelabs/awscli:latest
#   environment:
#     AWS_ACCESS_KEY_ID:
#       from_secret: {{ cookiecutter.aws_ci_access_key_name_prod }}
#     AWS_SECRET_ACCESS_KEY:
#       from_secret: {{ cookiecutter.aws_ci_secret_key_name_prod }}
#     S3_URL: s3://{{ cookiecutter.s3_bucket_prod }}
#     CDN_DISTRIBUTION_ID: {{ cookiecutter.cloudfront_dist_id_prod }}
#   commands:
#   - aws s3 rm $S3_URL/previous --recursive
#   - aws s3 mv $S3_URL/latest $S3_URL/previous --recursive
#   - aws s3 sync ./build $S3_URL/latest
#   - aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths "/*"
#   when:
#     branch: master
#     event:
#     - push
#     # - pull_request
